# SPDX-FileCopyrightText: GARDENA GmbH
#
# SPDX-License-Identifier: GPL-3.0-or-later

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
    - id: clippy
    - id: cargo-check

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.49.1
  hooks:
    - id: markdownlint-fix

- repo: https://github.com/crate-ci/typos
  rev: v1.50.2
  hooks:
    - id: typos

- repo: https://github.com/fsfe/reuse-tool
  rev: v6.2.0
  hooks:
    - id: reuse
